### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by MelyHC** [Grecia2727/lim20181-Track-FE-markdown-list#5]
Las funciones están bien separadas y cada una solo hace una cosa.
Te recomendaría tener en cuenta que estamos usando ECMAS6, podrías cambiar el for por un forOf, forIn , forEach y utiliza las arrowFunction , también ten en cuenta la diferencia entre const y let tienes algunas variables con let pero no las estas reasignando entonces deberían estar con const.
El nombre de tus funciones es descriptivo y en general has realizado un buen trabajo  👍

**Comment by Grecia2727** [comment]
Gracias Mel, por tus comentarios, los voy a tener en cuenta.
Saludos
